version: "3.9"

services:
    web:
        container_name: mysite_nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - fpm
            - mysql
    fpm:
        container_name: mysite_fpm
        environment:
            PHP_IDE_CONFIG: "serverName=mysite"
        build:
          dockerfile: docker/php/Dockerfile
          context: .
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        links:
            - mysql
    mysql:
        container_name: mysite_db
        image: mariadb:10.3
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mysite
    redis-07:
        container_name: redis-mysite
        image: redis:latest
        ports:
        -   "6379:6379"
